### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by luxigo** [doxel/doxel-uploader#3]
- [ ] check if camera is known by openMVG, ask the user to make a pull request if possible, and send a notification to the admin
- [ ] client-side auto-segmentation
- [ ] add a view with a single image per segment
- [ ] allow to split or merge segments
- [ ] send file list length before starting upload (so that the server don't start the toolchain when more files are to be uploaded)
- [ ] display authentication details to user in login/password inputs so that he can write them down or let the browser remember them 
- [ ] use strongloop for authentication and database access (backend and frontend)
- [ ] allow the user to specify an optional mail adress to receive notifications and to reset password
- [ ] allow the user to login with facebook, twitter, etc to authenticate and to receive notifications
- [ ] database migration to mongodb
- [ ] replace upload.php with javascript equivalent (fork node-plupload)

**Comment by bugdanov** [comment]
Thanks bro :-)

**Comment by luxigo** [comment]
welcome :-)  If I see something else I'll add it here too
